[2023-12-30T18:28:42.687+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: load_data.load_data_aisles manual__2023-12-30T18:28:37.263535+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
